package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "music")
public class Music {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String artist;
    @DynamoDBAttribute
    private int year;
    @DynamoDBAttribute
    private String web_url;
    @DynamoDBAttribute
    private String image_url;

    public Music(String title, String artist, int year, String web_url, String image_url) {
        this.title = title;
        this.artist = artist;
        this.year = year;
        this.web_url = web_url;
        this.image_url = image_url;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute
    public String getArtist() {
        return artist;
    }

    @DynamoDBAttribute
    public int getYear() {
        return year;
    }

    @DynamoDBAttribute
    public String getWeb_url() {
        return web_url;
    }

    @DynamoDBAttribute
    public String getImage_url() {
        return image_url;
    }
}
